
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Updated to the correct Supabase URL and key based on the network requests
const SUPABASE_URL = "https://aalbdeydgpallvcmmsvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhbGJkZXlkZ3BhbGx2Y21tc3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODQ5MzExNDMsImV4cCI6MjAwMDUwNzE0M30.ZRko5vEQTXUgLPeIgbBJ8NK7A9RJHtuY0apZyEXCDmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
